FORMAT: 1A
HOST: http://collabration.apiblueprint.org/

# Collabration API

Polls is a simple API allowing consumers to view polls and vote in them.

## Create New File [/api/collabration/file/creation]

### Create or upload new file [POST]

>Get element value by name in API:

<
form action="/api/collabration/file/creation" method="post" **enctype="multipart/form-data"**>

<
div>

<
input type="file" name="**_uploadExcelFile_**" />

<
input type="text" name="**_nameField_**" />

<
input type="text" name="**_customerField_**" />

<
input type="text" name="**_brandField_**" />

<
input type="text" name="**_yearField_**" />

<
input type="text" name="**_seasonField_**" />

<
/div>

<
input type="submit" value="submit" />  
<
/form>

+ Request

    + Headers
        
            Accept: application/json
            Authorization: Bearer 3sd413asd13a1a36s13a4faf3a1fs3f4as631,
            Content-Type : multipart/form-data; boundary

+ Response 200 (application/json)

        {
            "resultType": "success",
            "results": [
                {
                    "id": "1s6f1assdf1s655s31s",
                    "name": "EW44F #1",
                    "customerCode": "EBD",
                    "brandCode": "PYE",
                    "year": "2017",
                    "seasonCode": "SS",
                    "content": {
                        "header": [
                            {
                                "id": "1s63f4we65s6fsdf3s",
                                "text": "COMBO",
                                "value": "cb",
                                "type": "HL"
                            }
                        ],
                        "body": [
                            {
                                "id": "16ds4fs64f6sd41s3f1",
                                "line": "1",
                                "rows": [
                                    {
                                        "id": "3s16fsf16846s64vs6fs",
                                        "row": "1",
                                        "text": "AAA"
                                    }
                                ]
                            }
                        ]
                    }
                }
            ],
            "resultMsg": "",
            "exceptionDetail": ""
        }

## Fabric Item Master [/api/collabration/fabricitemmaster]

### Get Fabric Item Master [GET]

>get fabric item master data

+ Request (application/json)

    + Headers
        
            Accept: application/json
            Authorization: Bearer 3sd413asd13a1a36s13a4faf3a1fs3f4as631

+ Response 200 (application/json)

        {
            "resultType": "success",
            "results": [
                {
                    "type": "HL",
                    "label": "COMBO",
                    "value": "cb"
                }
            ],
            "resultMsg": "",
            "exceptionDetail": ""
        }

## File Content [/api/collabration/filecontent/{id}]

### Get File Content [GET]

>get file content by file id

+ Request (application/json)

    + Headers
        
            Accept: application/json
            Authorization: Bearer 3sd413asd13a1a36s13a4faf3a1fs3f4as631

+ Response 200 (application/json)

        {
            "resultType": "success",
            "results": [
                {
                    "id": "1s6f1assdf1s655s31s",
                    "name": "EW44F #1",
                    "customerCode": "EBD",
                    "brandCode": "PYE",
                    "year": "2017",
                    "seasonCode": "SS",
                    "content": {
                        "header": [
                            {
                                "id": "1s63f4we65s6fsdf3s",
                                "text": "COMBO",
                                "value": "cb",
                                "type": "HL"
                            }
                        ],
                        "body": [
                            {
                                "id": "16ds4fs64f6sd41s3f1",
                                "line": "1",
                                "rows": [
                                    {
                                        "id": "3s16fsf16846s64vs6fs",
                                        "row": "1",
                                        "text": "AAA"
                                    }
                                ]
                            }
                        ]
                    }
                }
            ],
            "resultMsg": "",
            "exceptionDetail": ""
        }

## All Files [/api/collabration/files]

### Get All Files [GET]

>get files by user role

+ Request (application/json)

    + Headers
        
            Accept: application/json
            Authorization: Bearer 3sd413asd13a1a36s13a4faf3a1fs3f4as631

+ Response 200 (application/json)

        {
            "resultType": "success",
            "results": [
                {
                    "customerCode": "EBD",
                    "brandCode": "PYE",
                    "yearSeasons": [
                        {
                            "year": "2017",
                            "seasonCode": "SS",
                            "yearSeasonCode": "2017 SS",
                            "files": [
                                {
                                    "fileId": "3s4d6fss46d4sfef6v",
                                    "name": "EW44F #1",
                                    "lastModifiedAt": "2017-04-12 15:23:65"
                                }, {
                                    "fileId": "6341D1S6F1132SE61S",
                                    "filename": "EW44F #2",
                                    "lastModifiedAt": "2017-04-10 15:23:65"
                                }
                            ]
                        }
                    ]
                }
            ],
            "resultMsg": "",
            "exceptionDetail": ""
        }

## Recent Files [/api/collabration/files/{pagesize}]

### Get Recent Files [GET]

>get recent files by user role

+ Request (application/json)

    + Headers
        
            Accept: application/json
            Authorization: Bearer 3sd413asd13a1a36s13a4faf3a1fs3f4as631

+ Response 200 (application/json)

        {
            "resultType": "success",
            "results": [
                {
                    "brand": "PYE",
                    "yearSeasons": [
                        {
                            "yearSeasonCode": "2017 SS",
                            "files": [
                                {
                                    "fileId": "3s4d6fss46d4sfef6v",
                                    "filename": "EW44F #1",
                                    "lastModifiedAt": "2017-04-12 15:23:65"
                                }, {
                                    "fileId": "6341D1S6F1132SE61S",
                                    "filename": "EW44F #2",
                                    "lastModifiedAt": "2017-04-10 15:23:65"
                                }
                            ]
                        }
                    ]
                }
            ],
            "resultMsg": "",
            "exceptionDetail": ""
        }